import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

// --- Skill Definitions (Mock Data) ---
const SKILL_DEFINITIONS = [
  {
    id: "ai-ml",
    title: "Artificial Intelligence & ML",
    category: "Tech & Data",
    students: "45,210",
    rating: 4.9,
    reviews: "12k+",
    growthLabel: "🔥 Explosive Growth (+35% YoY)",
    salary: { min: 110000, median: 145000, max: 195000 },
    jobCount: 12400,
  },
  {
    id: "frontend-dev",
    title: "Frontend Web Development",
    category: "Tech & Data",
    students: "82,400",
    rating: 4.8,
    reviews: "24k+",
    growthLabel: "High Demand (+15% YoY)",
    salary: { min: 65000, median: 90000, max: 130000 },
    jobCount: 35000,
  },
  {
    id: "cloud-devops",
    title: "Cloud Computing & DevOps",
    category: "Tech & Data",
    students: "32,150",
    rating: 4.8,
    reviews: "8.5k+",
    growthLabel: "High Demand (+18% YoY)",
    salary: { min: 100000, median: 130000, max: 175000 },
    jobCount: 9800,
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity & InfoSec",
    category: "Tech & Data",
    students: "28,400",
    rating: 4.9,
    reviews: "6.2k+",
    growthLabel: "🔥 Critical Shortage (+28% YoY)",
    salary: { min: 90000, median: 120000, max: 165000 },
    jobCount: 8200,
  },
  {
    id: "data-science",
    title: "Data Science & Analytics",
    category: "Tech & Data",
    students: "52,800",
    rating: 4.7,
    reviews: "15k+",
    growthLabel: "Steady Growth (+15% YoY)",
    salary: { min: 85000, median: 115000, max: 160000 },
    jobCount: 11500,
  },
  {
    id: "ux-ui",
    title: "UX/UI Design",
    category: "Creative & Design",
    students: "38,900",
    rating: 4.9,
    reviews: "9.3k+",
    growthLabel: "Steady Growth (+12% YoY)",
    salary: { min: 70000, median: 95000, max: 135000 },
    jobCount: 6400,
  },
  {
    id: "product-management",
    title: "Product Management",
    category: "Business & Strategy",
    students: "21,300",
    rating: 4.8,
    reviews: "5.1k+",
    growthLabel: "High Demand (+20% YoY)",
    salary: { min: 85000, median: 110000, max: 155000 },
    jobCount: 7600,
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    category: "Marketing & Creative",
    students: "65,100",
    rating: 4.7,
    reviews: "18k+",
    growthLabel: "High Demand (+22% YoY)",
    salary: { min: 50000, median: 75000, max: 110000 },
    jobCount: 22000,
  },
  {
    id: "seo-specialist",
    title: "SEO & Search Marketing",
    category: "Marketing & Creative",
    students: "31,200",
    rating: 4.8,
    reviews: "7.4k+",
    growthLabel: "Steady Growth (+14% YoY)",
    salary: { min: 55000, median: 72000, max: 105000 },
    jobCount: 14500,
  },
  {
    id: "copywriting",
    title: "Direct Response Copywriting",
    category: "Marketing & Creative",
    students: "19,200",
    rating: 4.8,
    reviews: "4.8k+",
    growthLabel: "High Demand (+14% YoY)",
    salary: { min: 55000, median: 85000, max: 120000 },
    jobCount: 4100,
  },
  {
    id: "ugc-creation",
    title: "UGC Content Creation",
    category: "Marketing & Creative",
    students: "24,500",
    rating: 4.7,
    reviews: "7.1k+",
    growthLabel: "🔥 Rapid Growth (+45% YoY)",
    salary: { min: 40000, median: 70000, max: 110000 },
    jobCount: 5300,
  },
  {
    id: "video-editing",
    title: "Video Editing & Motion Graphics",
    category: "Creative & Design",
    students: "42,300",
    rating: 4.9,
    reviews: "11k+",
    growthLabel: "🔥 Explosive Growth (+38% YoY)",
    salary: { min: 45000, median: 68000, max: 100000 },
    jobCount: 18500,
  },
  {
    id: "tech-sales",
    title: "Tech Sales & SDR",
    category: "Business & Strategy",
    students: "18,400",
    rating: 4.6,
    reviews: "4.2k+",
    growthLabel: "High Demand (+25% YoY)",
    salary: { min: 60000, median: 85000, max: 150000 }, // High upside with commission
    jobCount: 28000,
  },
  {
    id: "it-support",
    title: "IT Helpdesk & Support",
    category: "Tech & Data",
    students: "54,200",
    rating: 4.7,
    reviews: "16k+",
    growthLabel: "Steady Growth (+8% YoY)",
    salary: { min: 45000, median: 55000, max: 75000 },
    jobCount: 42000,
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering",
    category: "Emerging Tech",
    students: "15,600",
    rating: 4.6,
    reviews: "3.2k+",
    growthLabel: "🔥 Explosive Growth (+85% YoY)",
    salary: { min: 80000, median: 105000, max: 150000 },
    jobCount: 3200,
  },
];

export async function GET() {
  // Simply return the static mock data immediately
  const skills = SKILL_DEFINITIONS.map(s => ({
    ...s,
    isLive: false // Always false since we removed the API
  }));
  
  return NextResponse.json({ skills, cached: false, live: false });
}

